#!/usr/bin/env python3
"""
Generate affine elimination template for deterministic algebraic consensus.

The script derives closed-form expressions for the affine transformation
parameters given three point correspondences. It writes a runtime helper
module (`sfm/core/affine_template.py`) that evaluates the template using
pure NumPy operations.

Run:
    python sfm/tools/generate_affine_template.py
"""

from pathlib import Path
import textwrap
import sympy as sp
from sympy.printing.pycode import pycode


CORE_DIR = Path(__file__).resolve().parents[1] / "core"
OUTPUT_PATH = CORE_DIR / "affine_template.py"


def derive_template():
    """Derive symbolic expressions for affine parameters."""
    # Symbolic coordinates for three correspondences
    x1, y1, x2, y2, x3, y3 = sp.symbols("x1 y1 x2 y2 x3 y3")
    X1, Y1, X2, Y2, X3, Y3 = sp.symbols("X1 Y1 X2 Y2 X3 Y3")

    a11, a12, a21, a22, tx, ty = sp.symbols("a11 a12 a21 a22 tx ty")

    pts_src = [sp.Matrix([x1, y1]), sp.Matrix([x2, y2]), sp.Matrix([x3, y3])]
    pts_dst = [sp.Matrix([X1, Y1]), sp.Matrix([X2, Y2]), sp.Matrix([X3, Y3])]

    A = sp.Matrix([[a11, a12], [a21, a22]])
    t = sp.Matrix([tx, ty])

    equations = []
    for ps, pd in zip(pts_src, pts_dst):
        residual = pd - (A * ps + t)
        equations.extend(list(residual))

    solution = sp.solve(
        equations,
        (a11, a12, a21, a22, tx, ty),
        simplify=True,
        dict=True
    )[0]

    numerators = {}
    denominator = None
    for var, expr in solution.items():
        num, den = sp.fraction(sp.simplify(expr))
        if denominator is None:
            denominator = sp.factor(den)
        else:
            assert sp.simplify(denominator - den) == 0, "Inconsistent denominators"
        numerators[var] = sp.simplify(num)

    return numerators, denominator


def emit_runtime_module(numerators, denominator):
    """Write runtime helper module using derived expressions."""
    header = textwrap.dedent("""
        \"\"\"
        Auto-generated affine elimination template.

        This file is generated by `sfm/tools/generate_affine_template.py`.
        Do not edit manually.
        \"\"\"

        from __future__ import annotations

        from typing import Tuple

        import numpy as np


        def evaluate_affine_template(
            src_pts: np.ndarray,
            dst_pts: np.ndarray,
            eps: float = 1e-12
        ) -> Tuple[np.ndarray, np.ndarray, float]:
            \"\"\"
            Compute affine transformation parameters for three correspondences.

            Args:
                src_pts: (3, 2) array of source points
                dst_pts: (3, 2) array of destination points
                eps: Degeneracy threshold on the template denominator

            Returns:
                Tuple of (A, t, denom) where:
                    A: (2, 2) affine matrix
                    t: (2,) translation vector
                    denom: Template denominator (useful for diagnostics)
            \"\"\"
            x1, y1 = src_pts[0]
            x2, y2 = src_pts[1]
            x3, y3 = src_pts[2]

            X1, Y1 = dst_pts[0]
            X2, Y2 = dst_pts[1]
            X3, Y3 = dst_pts[2]
    """).strip()

    footer_block = textwrap.dedent("""
        if abs(denom) < eps:
            raise ValueError(f\"Degenerate configuration (denom={denom:.3e})\")

        inv_denom = 1.0 / denom
        a11 = a11_num * inv_denom
        a12 = a12_num * inv_denom
        a21 = a21_num * inv_denom
        a22 = a22_num * inv_denom
        tx = tx_num * inv_denom
        ty = ty_num * inv_denom

        A = np.array([[a11, a12], [a21, a22]], dtype=np.float64)
        t = np.array([tx, ty], dtype=np.float64)

        return A, t, denom
    """).strip()
    footer = textwrap.indent(footer_block, "    ")

    denominator_code = pycode(denominator)
    body_lines = [f"    denom = {denominator_code}"]

    for name in ["a11", "a12", "a21", "a22", "tx", "ty"]:
        expr = pycode(numerators[sp.Symbol(name)])
        body_lines.append(f"    {name}_num = {expr}")

    body = "\n".join(body_lines)

    module_text = header + "\n" + body + "\n" + footer

    OUTPUT_PATH.write_text(module_text + "\n", encoding="utf-8")
    print(f"[generate_affine_template] Wrote {OUTPUT_PATH}")


def main():
    numerators, denominator = derive_template()
    emit_runtime_module(numerators, denominator)


if __name__ == "__main__":
    main()
