"""
Auto-generated affine elimination template.

This file is generated by `sfm/tools/generate_affine_template.py`.
Do not edit manually.
"""

from __future__ import annotations

from typing import Tuple

import numpy as np


def evaluate_affine_template(
    src_pts: np.ndarray,
    dst_pts: np.ndarray,
    eps: float = 1e-12
) -> Tuple[np.ndarray, np.ndarray, float]:
    """
    Compute affine transformation parameters for three correspondences.

    Args:
        src_pts: (3, 2) array of source points
        dst_pts: (3, 2) array of destination points
        eps: Degeneracy threshold on the template denominator

    Returns:
        Tuple of (A, t, denom) where:
            A: (2, 2) affine matrix
            t: (2,) translation vector
            denom: Template denominator (useful for diagnostics)
    """
    x1, y1 = src_pts[0]
    x2, y2 = src_pts[1]
    x3, y3 = src_pts[2]

    X1, Y1 = dst_pts[0]
    X2, Y2 = dst_pts[1]
    X3, Y3 = dst_pts[2]
    denom = x1*y2 - x1*y3 - x2*y1 + x2*y3 + x3*y1 - x3*y2
    a11_num = X1*y2 - X1*y3 - X2*y1 + X2*y3 + X3*y1 - X3*y2
    a12_num = -X1*x2 + X1*x3 + X2*x1 - X2*x3 - X3*x1 + X3*x2
    a21_num = Y1*y2 - Y1*y3 - Y2*y1 + Y2*y3 + Y3*y1 - Y3*y2
    a22_num = -Y1*x2 + Y1*x3 + Y2*x1 - Y2*x3 - Y3*x1 + Y3*x2
    tx_num = X1*x2*y3 - X1*x3*y2 - X2*x1*y3 + X2*x3*y1 + X3*x1*y2 - X3*x2*y1
    ty_num = Y1*x2*y3 - Y1*x3*y2 - Y2*x1*y3 + Y2*x3*y1 + Y3*x1*y2 - Y3*x2*y1
    if abs(denom) < eps:
        raise ValueError(f"Degenerate configuration (denom={denom:.3e})")

    inv_denom = 1.0 / denom
    a11 = a11_num * inv_denom
    a12 = a12_num * inv_denom
    a21 = a21_num * inv_denom
    a22 = a22_num * inv_denom
    tx = tx_num * inv_denom
    ty = ty_num * inv_denom

    A = np.array([[a11, a12], [a21, a22]], dtype=np.float64)
    t = np.array([tx, ty], dtype=np.float64)

    return A, t, denom
