"""
Gröbner Basis Solver for Geometric Consensus

This module implements algebraic elimination using Gröbner bases to solve
polynomial systems arising from affine transformation constraints.

Mathematical Framework:
    - Ideal I = ⟨g₁, ..., gₙ⟩ generated by constraint polynomials
    - Gröbner basis G: reduced generator set with elimination properties
    - Hilbert's Nullstellensatz: 1 ∈ I ⟺ System is inconsistent

References:
    - Cox, Little, O'Shea: "Ideals, Varieties, and Algorithms" (2015)
    - Buchberger: "Gröbner Bases: An Algorithmic Method" (1965)

Author: Claude Code
Date: 2025-10-30
"""

from dataclasses import dataclass
from typing import List, Optional, Tuple
from enum import Enum
import numpy as np

from sympy import groebner, solve, Integer
from sympy.core.expr import Expr
from sympy.core.symbol import Symbol
from sympy.polys.polytools import GroebnerBasis

from .polynomial_system import (
    Correspondence,
    AffineTransformation,
    PolynomialSystemBuilder
)
from .affine_template import evaluate_affine_template


class ConsistencyStatus(Enum):
    """Status of polynomial system consistency check."""
    CONSISTENT = "consistent"  # Unique solution exists
    INCONSISTENT = "inconsistent"  # No solution (1 ∈ I)
    UNDERDETERMINED = "underdetermined"  # Infinite solutions
    DEGENERATE = "degenerate"  # Degenerate configuration


@dataclass
class GroebnerResult:
    """
    Result from Gröbner basis computation.

    Attributes:
        status: Consistency status of the system
        transformation: Solved affine transformation (if consistent)
        groebner_basis: Computed Gröbner basis
        certificate: Algebraic certificate (for inconsistent systems)
    """
    status: ConsistencyStatus
    transformation: Optional[AffineTransformation] = None
    groebner_basis: Optional[GroebnerBasis] = None
    certificate: Optional[str] = None


class GroebnerSolver:
    """
    Solver for polynomial systems using Gröbner basis elimination.

    This class implements Theorem 1 from the paper:
        "A polynomial system has a solution ⟺ 1 ∉ I (ideal)"
    """

    def __init__(
        self,
        monomial_order: str = 'lex',
        numerical_threshold: float = 1e-6,
        use_template: bool = True
    ):
        """
        Initialize Gröbner basis solver.

        Args:
            monomial_order: Monomial ordering for Gröbner basis
                - 'lex': Lexicographic (best for elimination)
                - 'grlex': Graded lexicographic (faster)
                - 'grevlex': Graded reverse lexicographic
            numerical_threshold: Threshold for numerical zero
            use_template: Use precomputed elimination template in closed form solver
        """
        self.monomial_order = monomial_order
        self.numerical_threshold = numerical_threshold
        self.use_template = use_template
        self.builder = PolynomialSystemBuilder()

    def solve_minimal_set(
        self,
        correspondences: List[Correspondence]
    ) -> GroebnerResult:
        """
        Solve polynomial system for minimal set (3 correspondences for affine).

        This is the core of Theorem 1: Check if 1 ∈ I via Gröbner basis.

        Args:
            correspondences: List of exactly 3 correspondences

        Returns:
            GroebnerResult with status and transformation (if exists)
        """
        if len(correspondences) != 3:
            return GroebnerResult(
                status=ConsistencyStatus.UNDERDETERMINED,
                certificate="Minimal set requires exactly 3 correspondences"
            )

        # Check for degeneracy
        from .polynomial_system import validate_minimal_set
        if not validate_minimal_set(correspondences):
            return GroebnerResult(
                status=ConsistencyStatus.DEGENERATE,
                certificate="Collinear points (degenerate configuration)"
            )

        # Build polynomial system
        polynomials = self.builder.build_affine_constraints(correspondences)
        variables = self.builder.variables

        try:
            # Compute Gröbner basis (Buchberger's algorithm)
            gb = groebner(
                polynomials,
                variables,
                order=self.monomial_order
            )

            # Check consistency: 1 ∈ I?
            if Integer(1) in gb:
                return GroebnerResult(
                    status=ConsistencyStatus.INCONSISTENT,
                    groebner_basis=gb,
                    certificate="Gröbner basis contains 1 (no solution exists)"
                )

            # Solve for transformation parameters
            solution = solve(list(gb), variables)

            if not solution:
                return GroebnerResult(
                    status=ConsistencyStatus.UNDERDETERMINED,
                    groebner_basis=gb,
                    certificate="Gröbner basis computed but no unique solution"
                )

            # Handle multiple solutions (rare for minimal sets)
            if isinstance(solution, list):
                # Take first solution
                solution = solution[0]

            # Convert symbolic solution to numerical transformation
            transformation = self.builder.symbolic_to_numerical(solution)

            # Validate transformation (det(A) ≠ 0)
            det = np.linalg.det(transformation.A)
            if abs(det) < self.numerical_threshold:
                return GroebnerResult(
                    status=ConsistencyStatus.DEGENERATE,
                    transformation=transformation,
                    groebner_basis=gb,
                    certificate=f"Singular transformation (det={det:.2e})"
                )

            return GroebnerResult(
                status=ConsistencyStatus.CONSISTENT,
                transformation=transformation,
                groebner_basis=gb,
                certificate="Unique affine transformation found"
            )

        except Exception as e:
            # Catch SymPy errors (e.g., timeout, numerical issues)
            return GroebnerResult(
                status=ConsistencyStatus.UNDERDETERMINED,
                certificate=f"Gröbner basis computation failed: {str(e)}"
            )

    def solve_closed_form(
        self,
        correspondences: List[Correspondence]
    ) -> GroebnerResult:
        """
        Solve affine transformation in closed form (faster than Gröbner basis).

        For 3 correspondences, affine transformation can be solved directly
        via linear system without symbolic computation.

        This is used as a fast path before falling back to Gröbner basis.

        Args:
            correspondences: List of exactly 3 correspondences

        Returns:
            GroebnerResult with solved transformation
        """
        if len(correspondences) != 3:
            return GroebnerResult(
                status=ConsistencyStatus.UNDERDETERMINED,
                certificate="Closed form requires exactly 3 correspondences"
            )

        # Check degeneracy
        from .polynomial_system import validate_minimal_set
        if not validate_minimal_set(correspondences):
            return GroebnerResult(
                status=ConsistencyStatus.DEGENERATE,
                certificate="Collinear points"
            )

        # Extract points
        src_pts = np.array([corr.p_src for corr in correspondences], dtype=np.float64)  # (3, 2)
        dst_pts = np.array([corr.p_dst for corr in correspondences], dtype=np.float64)  # (3, 2)

        try:
            if self.use_template:
                A, t, denom = evaluate_affine_template(src_pts, dst_pts)
                certificate = f"Template denominator={denom:.3e}"
            else:
                # Build linear system: dst = src @ A^T + t
                system_matrix = np.column_stack([src_pts, np.ones(3)])  # (3, 3)

                params_x = np.linalg.solve(system_matrix, dst_pts[:, 0])  # [a11, a21, tx]
                params_y = np.linalg.solve(system_matrix, dst_pts[:, 1])  # [a12, a22, ty]

                A = np.array([
                    [params_x[0], params_y[0]],
                    [params_x[1], params_y[1]]
                ])
                t = np.array([params_x[2], params_y[2]])
                certificate = "Closed-form linear solve"

            transformation = AffineTransformation(A=A, t=t)

            # Validate determinant
            det = np.linalg.det(A)
            if abs(det) < self.numerical_threshold:
                return GroebnerResult(
                    status=ConsistencyStatus.DEGENERATE,
                    transformation=transformation,
                    certificate=f"Singular transformation (det={det:.2e})"
                )

            return GroebnerResult(
                status=ConsistencyStatus.CONSISTENT,
                transformation=transformation,
                certificate=certificate
            )

        except (np.linalg.LinAlgError, ValueError) as e:
            return GroebnerResult(
                status=ConsistencyStatus.DEGENERATE,
                certificate=f"Linear system singular: {str(e)}"
            )

    def count_inliers(
        self,
        transformation: AffineTransformation,
        correspondences: List[Correspondence],
        threshold: float = 5.0
    ) -> Tuple[int, np.ndarray]:
        """
        Count inliers for a given transformation.

        Args:
            transformation: Affine transformation to test
            correspondences: List of all correspondences
            threshold: Inlier threshold (pixels)

        Returns:
            Tuple of (inlier_count, residuals)
        """
        residuals = self.builder.evaluate_residuals(transformation, correspondences)
        inliers = np.sum(residuals < threshold)
        return int(inliers), residuals

    def verify_certificate(
        self,
        correspondences: List[Correspondence],
        verbose: bool = False
    ) -> Tuple[bool, str]:
        """
        Verify algebraic certificate for inconsistent systems.

        For systems where 1 ∈ I, extract the algebraic proof that
        no transformation exists.

        Args:
            correspondences: List of correspondences
            verbose: Print detailed certificate

        Returns:
            Tuple of (is_inconsistent, certificate_string)
        """
        result = self.solve_minimal_set(correspondences)

        if result.status == ConsistencyStatus.INCONSISTENT:
            if verbose:
                print("=== Algebraic Certificate ===")
                print(f"Status: {result.status.value}")
                print(f"Gröbner basis: {result.groebner_basis}")
                print(f"Certificate: {result.certificate}")

            return True, result.certificate or "System inconsistent (1 ∈ I)"

        return False, "System is consistent or underdetermined"


def estimate_affine_2d_opencv(
    src_pts: np.ndarray,
    dst_pts: np.ndarray
) -> Optional[AffineTransformation]:
    """
    Estimate affine transformation using OpenCV (fallback for numerical stability).

    This provides a robust alternative when symbolic computation fails.

    Args:
        src_pts: Source points (Nx2)
        dst_pts: Destination points (Nx2)

    Returns:
        AffineTransformation or None if estimation fails
    """
    try:
        import cv2

        # Requires at least 3 points
        if len(src_pts) < 3:
            return None

        # Estimate affine transformation
        M, inliers = cv2.estimateAffinePartial2D(
            src_pts.astype(np.float32),
            dst_pts.astype(np.float32),
            method=cv2.RANSAC
        )

        if M is None:
            return None

        # Extract A and t from 2x3 matrix [A | t]
        A = M[:, :2]
        t = M[:, 2]

        return AffineTransformation(A=A, t=t)

    except ImportError:
        # OpenCV not available
        return None


if __name__ == "__main__":
    print("=== Gröbner Basis Solver Example ===\n")

    # Example 1: Consistent system (exact affine transformation)
    print("Example 1: Consistent system")
    correspondences = [
        Correspondence(
            p_src=np.array([0.0, 0.0]),
            p_dst=np.array([1.0, 2.0])
        ),
        Correspondence(
            p_src=np.array([1.0, 0.0]),
            p_dst=np.array([2.0, 3.0])
        ),
        Correspondence(
            p_src=np.array([0.0, 1.0]),
            p_dst=np.array([0.0, 3.0])
        )
    ]

    solver = GroebnerSolver()

    # Method 1: Closed-form (fast)
    result_closed = solver.solve_closed_form(correspondences)
    print(f"Closed-form status: {result_closed.status.value}")
    if result_closed.transformation:
        print(f"A =\n{result_closed.transformation.A}")
        print(f"t = {result_closed.transformation.t}")
        print(f"Rotation angle: {np.degrees(result_closed.transformation.rotation_angle):.2f}°")

    print("\n" + "="*50 + "\n")

    # Example 2: Inconsistent system (no affine transformation exists)
    print("Example 2: Inconsistent system")
    inconsistent_corrs = [
        Correspondence(
            p_src=np.array([0.0, 0.0]),
            p_dst=np.array([1.0, 1.0])
        ),
        Correspondence(
            p_src=np.array([1.0, 0.0]),
            p_dst=np.array([2.0, 1.0])
        ),
        Correspondence(
            p_src=np.array([0.0, 1.0]),
            p_dst=np.array([10.0, 10.0])  # Outlier!
        )
    ]

    result_inconsistent = solver.solve_closed_form(inconsistent_corrs)
    print(f"Status: {result_inconsistent.status.value}")
    print(f"Certificate: {result_inconsistent.certificate}")

    # Verify residuals
    if result_inconsistent.transformation:
        inliers, residuals = solver.count_inliers(
            result_inconsistent.transformation,
            inconsistent_corrs,
            threshold=5.0
        )
        print(f"\nInliers: {inliers}/3")
        print(f"Residuals: {residuals}")
